Add Review Feature in Public Toilet
atharvatechnology/ronb-node pull request #125
Opened 2023-01-20 11:06 UTC by Grunze1s

- Entity Creation
- Service for public toilet review
- Create, Update, FindOne, FindAll, Remove service and resolver for public toilet review
- Resolver for public toilet review

2023-01-23 10:42 UTC, shovan777 requested changes
Please make or debate the requested changes.

2023-01-23 10:42 UTC, shovan777 commented on src/public-toilet/public-toilet.resolver.ts
> +    @Roles(Role.Writer)
`Writer` should not be allowed to destroy any resource. But it will difficult if has to ask an `admin` each time he has to destroy a resource during its creation. Instead a more nuanced authorization where `writer` can destroy only those resources created by him/her and that are not published yet would be better.

2023-01-23 10:42 UTC, shovan777 commented on src/public-toilet/public-toilet.resolver.ts
> +            total_rating += reviews[review].rating;
what is `totalRating` here? Why not use `average rating` here?

2023-01-23 10:42 UTC, shovan777 commented on src/reviews/dto/create-reviews.input.ts
> +    @Field(() => Int, { description: 'Public Toilet id'})
Please add validations here instead of in entity files.

2023-01-23 10:42 UTC, shovan777 commented on src/reviews/entities/reviews.entity.ts
> +    @Min(0)
In my opinion validation like `Min` makes no sense here since, validation is done during input and input is done during creation/update. for ex: `CreatePublicToiletInput.ts`

2023-01-23 10:42 UTC, shovan777 commented on src/reviews/entities/reviews.entity.ts
> +    @Field(() => Int, { description: 'one wrote the review', })
why not use a compound private key like in `NewsLike` to ensure that each user can have a single review?

2023-01-23 10:42 UTC, shovan777 commented on src/reviews/entities/reviews.entity.ts
> +    @Field(() => Int, { description: 'one wrote the review', })
Note that @sazan10  in opposed to this. He claims it will add a complication where app needs to check for  `hasReviewed` state before a user is allowed to post a review.

2023-01-23 10:42 UTC, shovan777 commented on src/reviews/entities/reviews.entity.ts
> +    @Field(() => Float, { description: 'Total Rating' })
what is total rating/

2023-01-23 10:42 UTC, shovan777 commented on src/reviews/reviews.resolver.ts
> +
Add `findAllAdmin` with offset based pagination here @Grunze1s

2023-01-24 04:18 UTC, Grunze1s commented on src/public-toilet/public-toilet.resolver.ts
> +            total_rating += reviews[review].rating;
Ya it should be average it was a blunder. Fixed in [d71eaa3](https://github.com/atharvatechnology/ronb-node/pull/125/commits/d71eaa33c2c3619f6bfb31f27958bacfb9ae9639)

2023-01-24 04:28 UTC, Grunze1s commented on src/reviews/dto/create-reviews.input.ts
> +    @Field(() => Int, { description: 'Public Toilet id'})
OK but will not remove it from entity it might be used in the future. Fixed in [de10a2f](https://github.com/atharvatechnology/ronb-node/pull/125/commits/de10a2f08b69022e10b190b3904679c29c3fa860) Also remove nullable because if review is created rating is required to be provided. Fixed in [864d0ed](https://github.com/atharvatechnology/ronb-node/pull/125/commits/864d0ed9414b754f9294f7920a6b45b81ebcc62e)

2023-01-24 04:41 UTC, Grunze1s commented on src/reviews/entities/reviews.entity.ts
> +    @Min(0)
it the validation used in the db. as in [example](https://typeorm.biunav.com/en/validation.html) there was missing of calling validation while save so was not validated. it will be used in future so i haven't removed it.

2023-01-24 04:50 UTC, Grunze1s commented on src/reviews/entities/reviews.entity.ts
> +    @Field(() => Int, { description: 'one wrote the review', })
on one public toilet one user should be able to write only one review. that should be done.

2023-01-24 04:57 UTC, Grunze1s commented on src/reviews/entities/reviews.entity.ts
> +    @Field(() => Float, { description: 'Total Rating' })
it should be average rating. fixed in [d71eaa3](https://github.com/atharvatechnology/ronb-node/pull/125/commits/d71eaa33c2c3619f6bfb31f27958bacfb9ae9639)

2023-01-24 08:16 UTC, Grunze1s commented on src/public-toilet/public-toilet.resolver.ts
> +    @Roles(Role.Writer)
Added remove feature only to creator of the public toilet and only unpublished toilets can be deleted.Fixes in [32188aa](https://github.com/atharvatechnology/ronb-node/pull/125/commits/32188aab65d18a5ef7e542b0901929a06f083a9b)
Remaining -> delete functionality for admin user.

2023-01-24 08:17 UTC, Grunze1s commented on src/public-toilet/public-toilet.resolver.ts
> +    @Roles(Role.Writer)
Added remove feature only to creator of the public toilet and only unpublished toilets can be deleted.Fixes in [32188aa](https://github.com/atharvatechnology/ronb-node/pull/125/commits/32188aab65d18a5ef7e542b0901929a06f083a9b)
Remaining -> delete functionality for admin user.

2023-01-24 10:03 UTC, Grunze1s commented on src/reviews/entities/reviews.entity.ts
> +    @Field(() => Int, { description: 'one wrote the review', })
Fixes on [545a882](https://github.com/atharvatechnology/ronb-node/pull/125/commits/545a8821e133769e8bc1feb8ed7298efc92c93e4)

2023-01-25 08:09 UTC, Grunze1s commented on src/reviews/reviews.resolver.ts
> +
Added offset based pagination similar to yellow pages with custom response. Removed some field from the ObjectType which is not used by front end and generated error while requesting to back end. Fixes in [88c2f41](https://github.com/atharvatechnology/ronb-node/pull/125/commits/88c2f41911951722fbf8cdca6dade29ed901e548)

2023-01-25 08:29 UTC, Grunze1s commented
@shovan777 almost all the comments have been worked . Need a review.

2023-01-26 10:01 UTC, shovan777 approved these changes
Everything looks solid :100:

2023-01-26 10:03 UTC, merged